// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTQlSiZu5RfWBMEsAvzNAzg8yQyL0380',
    appId: '1:247001946565:web:38bf61e9f240a4e04113ac',
    messagingSenderId: '247001946565',
    projectId: 'uplb-easypay-2024',
    authDomain: 'uplb-easypay-2024.firebaseapp.com',
    storageBucket: 'uplb-easypay-2024.firebasestorage.app',
    measurementId: 'G-BK137XXRNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFPrJiGbVKhHvDbpuLqQGnD9i8RjvAWM',
    appId: '1:247001946565:android:bfdd823225d476254113ac',
    messagingSenderId: '247001946565',
    projectId: 'uplb-easypay-2024',
    storageBucket: 'uplb-easypay-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDTqjFwUb5kSm6KvZy6NNKetIJs2qOxkk',
    appId: '1:247001946565:ios:d5e3cc4249dd2b864113ac',
    messagingSenderId: '247001946565',
    projectId: 'uplb-easypay-2024',
    storageBucket: 'uplb-easypay-2024.firebasestorage.app',
    iosBundleId: 'com.example.easypayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDTqjFwUb5kSm6KvZy6NNKetIJs2qOxkk',
    appId: '1:247001946565:ios:d5e3cc4249dd2b864113ac',
    messagingSenderId: '247001946565',
    projectId: 'uplb-easypay-2024',
    storageBucket: 'uplb-easypay-2024.firebasestorage.app',
    iosBundleId: 'com.example.easypayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvTQlSiZu5RfWBMEsAvzNAzg8yQyL0380',
    appId: '1:247001946565:web:de679b2b27881ce44113ac',
    messagingSenderId: '247001946565',
    projectId: 'uplb-easypay-2024',
    authDomain: 'uplb-easypay-2024.firebaseapp.com',
    storageBucket: 'uplb-easypay-2024.firebasestorage.app',
    measurementId: 'G-QEXF7VMNHB',
  );
}
